import type { RidgeForecastWeights } from "../forecast-ridge.ts";

/** Generated by scripts/ml/train-forecast.mjs. Do not edit by hand. */
export const FORECAST_RIDGE_WEIGHTS: RidgeForecastWeights | null = {
  version: 1,
  featureNames: [
    "wd_sun",
    "wd_mon",
    "wd_tue",
    "wd_wed",
    "wd_thu",
    "wd_fri",
    "wd_sat",
    "dom_sin",
    "dom_cos",
    "month_start",
    "month_end",
    "since_payday",
    "payday_window",
    "trail7",
    "trail28",
    "same_weekday",
    "zero_share",
  ],
  intercept: 0.939328,
  coef: [
    0.005814, -0.117685, -0.031324, 0.178394, -0.126056, 0.114845, -0.023988, 0.128338, 0.022847,
    0.272202, -0.16575, 0.191818, 0.01795, -0.039165, 0.126277, -0.083198, -0.015026,
  ],
  lambda: 1000,
  trainedOn:
    "simulated people: 450 train + 150 validation (seeds train-0.., validation-0..), 324000 rows, 30-day horizon",
};
