/** Category keys, matching `categories.key` in the database. */
export const CATEGORY_KEYS = [
  "food",
  "transport",
  "recharge_data",
  "bills",
  "education",
  "shopping",
  "family",
  "health",
  "entertainment",
  "savings",
  "income",
  "other",
] as const;

export type CategoryKey = (typeof CATEGORY_KEYS)[number];

/** Categories counted as essential spending; mirrors `categories.is_essential` in the database. */
export const ESSENTIAL_CATEGORY_KEYS: readonly CategoryKey[] = [
  "food",
  "transport",
  "recharge_data",
  "bills",
  "education",
  "health",
];

export const isEssentialCategory = (key: CategoryKey) => ESSENTIAL_CATEGORY_KEYS.includes(key);

export const isCategoryKey = (v: unknown): v is CategoryKey =>
  typeof v === "string" && (CATEGORY_KEYS as readonly string[]).includes(v);

/**
 * Keyword dictionary (English and Bangla). Matching is case-insensitive; the longest matching
 * keyword wins, so "pathao food" beats "pathao". Latin keywords match on word boundaries.
 */
export const KEYWORDS: Record<Exclude<CategoryKey, "income" | "other">, string[]> = {
  food: [
    "foodpanda",
    "pathao food",
    "hungrynaki",
    "restaurant",
    "cafe",
    "tea stall",
    "biryani",
    "kacchi",
    "burger",
    "pizza",
    "kfc",
    "bakery",
    "grocery",
    "shwapno",
    "agora",
    "meena bazar",
    "meenabazar",
    "chaldal",
    "bazar",
    "fruit",
    "sweets",
    "mishti",
    "canteen",
    "lunch",
    "dinner",
    "breakfast",
    "চা",
    "খাবার",
    "বাজার",
    "রেস্টুরেন্ট",
    "হোটেল",
    "মুদি",
    "নাস্তা",
  ],
  transport: [
    "uber",
    "pathao",
    "obhai",
    "rickshaw",
    "cng",
    "bus fare",
    "bus",
    "metro",
    "train",
    "railway",
    "petrol",
    "fuel",
    "taxi",
    "launch",
    "পাঠাও",
    "রিকশা",
    "বাস",
    "সিএনজি",
    "ভাড়া",
  ],
  recharge_data: [
    "grameenphone",
    "robi",
    "banglalink",
    "airtel",
    "teletalk",
    "recharge",
    "data pack",
    "mobile data",
    "minutes",
    "gp",
    "রিচার্জ",
    "ডেটা",
    "ইন্টারনেট প্যাক",
    "গ্রামীণফোন",
    "রবি",
  ],
  bills: [
    "desco",
    "dpdc",
    "nesco",
    "wasa",
    "titas",
    "gas bill",
    "electricity",
    "prepaid meter",
    "wifi",
    "broadband",
    "internet bill",
    "link3",
    "carnival",
    "dish bill",
    "akash",
    "house rent",
    "rent",
    "বিদ্যুৎ",
    "গ্যাস",
    "পানির বিল",
    "বাসা ভাড়া",
    "ওয়াইফাই",
  ],
  education: [
    "tuition",
    "school",
    "college",
    "university",
    "coaching",
    "exam fee",
    "admission",
    "book",
    "stationery",
    "course",
    "udemy",
    "tutor",
    "টিউশন",
    "স্কুল",
    "কলেজ",
    "ভর্তি",
    "বই",
    "পরীক্ষা",
  ],
  shopping: [
    "daraz",
    "aarong",
    "bata",
    "apex",
    "clothes",
    "shirt",
    "fashion",
    "electronics",
    "ryans",
    "star tech",
    "shopping",
    "mall",
    "gadget",
    "shoes",
    "কেনাকাটা",
    "জামা",
    "জুতা",
  ],
  family: [
    "family",
    "mother",
    "father",
    "ammu",
    "abbu",
    "brother",
    "sister",
    "wife",
    "remittance",
    "gift",
    "friend",
    "loan return",
    "মা",
    "বাবা",
    "পরিবার",
    "ভাই",
    "বোন",
    "ধার",
  ],
  health: [
    "pharmacy",
    "medicine",
    "hospital",
    "clinic",
    "doctor",
    "labaid",
    "square hospital",
    "diagnostic",
    "dental",
    "lab test",
    "ওষুধ",
    "হাসপাতাল",
    "ডাক্তার",
    "ফার্মেসি",
  ],
  entertainment: [
    "netflix",
    "spotify",
    "youtube",
    "hoichoi",
    "bioscope",
    "cinema",
    "movie",
    "cineplex",
    "game",
    "steam",
    "pubg",
    "free fire",
    "concert",
    "বিনোদন",
    "সিনেমা",
    "গেম",
  ],
  savings: ["savings", "dps", "fdr", "sanchay", "সঞ্চয়", "ডিপিএস"],
};
